/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.List;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author willian
 */
public class ViewMinefield extends javax.swing.JFrame {

    /**
     * Creates new form ViewMinefield
     */
    
    private int linha, coluna,minas;
    private  Map<String,JButton> botoes = new HashMap<String,JButton>();
    
    public ViewMinefield(int linha, int coluna) {
        this.linha = linha;
        this.coluna = coluna;
        initComponents();
        initMinefield(this.linha, this.coluna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMapa = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();
        lblBandeira = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMapa.setToolTipText("");
        pnlMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMapa.setFocusable(false);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setToolTipText("");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setText("0/0");

        lblBandeira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBandeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CampoMinadoAviso.png"))); // NOI18N

        javax.swing.GroupLayout pnlMapaLayout = new javax.swing.GroupLayout(pnlMapa);
        pnlMapa.setLayout(pnlMapaLayout);
        pnlMapaLayout.setHorizontalGroup(
            pnlMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBandeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMapaLayout.createSequentialGroup()
                        .addComponent(btnReiniciar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMapaLayout.setVerticalGroup(
            pnlMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMapaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnReiniciar)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContador)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(pnlMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(pnlMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
//Get e Set
    
    public int getLinha() {
        return linha;
    }

    public void setLinha(int linha) {
        this.linha = linha;
    }

    public int getColuna() {
        return coluna;
    }

    public void setColuna(int coluna) {
        this.coluna = coluna;
    }

    public int getMinas() {
        return minas;
    }

    public void setMinas(int minas) {
        this.minas = minas;
    }

    public Map<String, JButton> getBotoes() {
        return botoes;
    }
        public JButton getBotaoMapa(String i) {
        return botoes.get(i);
    }

    public void setBotoes(Map<String, JButton> botoes) {
        this.botoes = botoes;
        for(int i = 0; i<botoes.size();i++)
            getContentPane().add(botoes.get(Integer.toString(i)));
    }

    public JButton getBtnReiniciar() {
        return btnReiniciar;
    }

    public void setBtnReiniciar(JButton btnReiniciar) {
        this.btnReiniciar = btnReiniciar;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JLabel getLblBandeira() {
        return lblBandeira;
    }

    public void setLblBandeira(JLabel lblBandeira) {
        this.lblBandeira = lblBandeira;
    }

    public JLabel getLblContador() {
        return lblContador;
    }

    public void setLblContador(JLabel lblContador) {
        this.lblContador = lblContador;
    }

    public JPanel getPnlMapa() {
        return pnlMapa;
    }

    public void setPnlMapa(JPanel pnlMapa) {
        this.pnlMapa = pnlMapa;
        getContentPane().add(pnlMapa, new GridBagConstraints());
    }
    
     private void initMinefield(int linha, int coluna) {
        JButton btnTemp;  
        String indice;
        
        //Um Gambi Pattern basico
        this.setSize(((coluna+1)*28)+130,((linha+1)*28)+60);
        pnlMapa.setLocation((coluna+1)*28+15,10);
        this.add(pnlMapa, new GridBagConstraints());
        //fim GP
        
        
        this.setLocationRelativeTo(null);
        
        for (int i = 0; i <linha;i++){  
            for(int j = 0; j < coluna; j++){
                btnTemp = new JButton();  
                btnTemp.setFocusable(false);
                btnTemp.setText("");
                btnTemp.setBounds((j+1)*28,(i+1)*28,30,30);
                btnTemp.setVisible(true);
                //incluindo o botão no map com um rotulo, iniciando de 0
                indice = (Integer.toString(i)+","+Integer.toString(j));
                botoes.put(indice, btnTemp); 
                //add o botao no JFrame
                 getContentPane().add(botoes.get(indice));
                System.out.print(indice+"  ");
             }
                System.out.println(" ");
           } 
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblBandeira;
    private javax.swing.JLabel lblContador;
    private javax.swing.JPanel pnlMapa;
    // End of variables declaration//GEN-END:variables
}
