/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.List;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author willian
 */
public class ViewMinefield extends javax.swing.JFrame {

    /**
     * Creates new form ViewMinefield
     */
    
    private int linha, coluna,minas;
    private  Map<String,JButton> botoes = new HashMap<String,JButton>();
    
    public ViewMinefield(int linha, int coluna) {
        initComponents();
        initMinefield(linha,coluna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void initMinefield(int linha, int coluna) {
        int indice = 0;
        JButton btnTemp;  
        for (int i = 0; i <linha;i++){  
            for(int j = 0; j < coluna; j++){
                System.out.print(j +"  ");
                btnTemp = new JButton();  
                //incluindo o botão no map com um rotulo, iniciando de 0
                botoes.put(Integer.toString(indice), btnTemp); 
                //assumindo que i.getNome() devolve um nome único para cada programa
                  botoes.get(Integer.toString(indice)).setText("");
                 botoes.get(Integer.toString(indice)).setBounds(j*30,i*30,30,30);
                 botoes.get(Integer.toString(indice)).setVisible(true);
                 //botoes.get(Integer.toString(indice)).setSe(true);
                  getContentPane().add(botoes.get(Integer.toString(indice)));
                  //botoes.get(Integer.toString(indice)).setLocation();
                  indice++;
             }
                System.out.println(" ");
           } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
